import { Injectable } from "@nestjs/common";
import { PrismaService } from "../../database/prisma.service";

/**
 * Read-only audit aggregator. Pulls the actions that already carry a
 * `created_by` stamp (Consumption ledger entries + InventoryMovement
 * rows) and merges them into a single chronological feed. We purposefully
 * keep this as a query-side concern: there is no separate `audit_log`
 * table, no triggers, no double-write. The two underlying tables are
 * already authoritative — this view just joins them at read time.
 *
 * Event kinds emitted:
 *   - bill_adjustment   (Consumption.type = adjustment | discount)
 *   - refund            (Consumption.type = refund)
 *   - inventory_restock (InventoryMovement.type = restock)
 *   - inventory_waste   (InventoryMovement.type = waste)
 *   - inventory_adjust  (InventoryMovement.type = correction)
 */
export type AuditEventKind =
  | "bill_adjustment"
  | "refund"
  | "inventory_restock"
  | "inventory_waste"
  | "inventory_adjust";

export interface AuditEvent {
  id: string;
  kind: AuditEventKind;
  created_at: string;
  created_by: string | null;
  /** Free-form summary the UI can render directly. */
  summary: string;
  /** When set, points at the Bill drawer (sessionId) or product. */
  context: {
    session_id?: number;
    product_id?: number;
    product_name?: string;
    table_id?: number;
    amount?: number;
  };
}

@Injectable()
export class AuditLogService {
  constructor(private readonly prisma: PrismaService) {}

  async list(limit = 100): Promise<AuditEvent[]> {
    const safeLimit = Math.min(Math.max(1, limit), 500);

    // Fetch a window from each table independently. We slice each at
    // safeLimit so the merged output never exceeds 2x; the caller still
    // gets back at most safeLimit after the global sort.
    const [consumptions, inventory] = await Promise.all([
      this.prisma.consumption.findMany({
        where: {
          // Only the manually-created ones are interesting for audit.
          // Consumption rows generated by an order being delivered have
          // `created_by` = null (system-generated) and aren't useful here.
          created_by: { not: null },
        },
        orderBy: { created_at: "desc" },
        take: safeLimit,
        include: {
          table_session: {
            select: { id: true, table_id: true },
          },
        },
      }),
      this.prisma.inventoryMovement.findMany({
        orderBy: { created_at: "desc" },
        take: safeLimit,
        include: {
          product: { select: { id: true, name: true } },
        },
      }),
    ]);

    const events: AuditEvent[] = [];

    for (const c of consumptions) {
      const kind: AuditEventKind =
        c.type === "refund" ? "refund" : "bill_adjustment";
      events.push({
        id: `consumption:${c.id}`,
        kind,
        created_at: c.created_at.toISOString(),
        created_by: c.created_by,
        summary: this.summarizeConsumption(
          kind,
          c.type,
          c.description,
          Number(c.amount),
          c.reason,
        ),
        context: {
          session_id: c.table_session_id,
          table_id: c.table_session?.table_id,
          amount: Number(c.amount),
        },
      });
    }

    for (const m of inventory) {
      const kind: AuditEventKind =
        m.type === "restock"
          ? "inventory_restock"
          : m.type === "waste"
            ? "inventory_waste"
            : "inventory_adjust";
      events.push({
        id: `inventory:${m.id}`,
        kind,
        created_at: m.created_at.toISOString(),
        created_by: m.created_by,
        summary: this.summarizeInventory(
          m.type,
          m.product?.name ?? `producto #${m.product_id}`,
          m.quantity,
          m.reason,
        ),
        context: {
          product_id: m.product_id,
          product_name: m.product?.name ?? null,
          amount: m.quantity,
        },
      });
    }

    events.sort((a, b) => b.created_at.localeCompare(a.created_at));
    return events.slice(0, safeLimit);
  }

  private summarizeConsumption(
    kind: AuditEventKind,
    type: string,
    description: string,
    amount: number,
    reason: string | null,
  ): string {
    const reasonSuffix = reason ? ` — ${reason}` : "";
    if (kind === "refund") {
      return `Reembolso de ${description} (${formatCop(amount)})${reasonSuffix}`;
    }
    if (type === "discount") {
      return `Descuento "${description}" (${formatCop(amount)})${reasonSuffix}`;
    }
    return `Ajuste "${description}" (${formatCop(amount)})${reasonSuffix}`;
  }

  private summarizeInventory(
    type: string,
    productName: string,
    quantity: number,
    reason: string | null,
  ): string {
    const reasonSuffix = reason ? ` — ${reason}` : "";
    const sign = quantity > 0 ? "+" : "";
    if (type === "restock") {
      return `Reposición de ${productName} (${sign}${quantity})${reasonSuffix}`;
    }
    if (type === "waste") {
      return `Merma de ${productName} (${sign}${quantity})${reasonSuffix}`;
    }
    return `Corrección de stock en ${productName} (${sign}${quantity})${reasonSuffix}`;
  }
}

function formatCop(n: number) {
  return new Intl.NumberFormat("es-CO", {
    style: "currency",
    currency: "COP",
    maximumFractionDigits: 0,
  }).format(n);
}
